task 0x05-pyhton-exceptions readme
